dist: xenial
branches:
  only:
  - master
  - develop
language: java
jdk:
- openjdk11
node_js: '10'
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - script:
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/candidate-questions/server-questions && mvn clean install
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/candidate-questions/client-questions && npm install
      && npm run lint
      && npm run test
      && npm run build
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/documentation-questions && mvn clean install
stages:
- test
notifications:
  slack:
    secure: xhuIPz8DpmBhgivWajgpB0crqv67ltbihIaFuW0lPOVHp5L7kmd/pwE1yS4ncR7dNrh622yaxEKuLsGL4zX2Va1JbcifDy9VxRajErVmZiGUEedblddSZACE7DdVAk0xmvNQxdmPeCKggx0MeErvSOeW9GzqmLAWPXHn9Fo1j4VZ8+xXVlQnNcMvVzARtKB5ndwsJOKH/MGM71MD6ZpfaV2lrVISMuJyKAl6btWdwuGS6WhjwK5b4vv7FGHw19lRJwQiJQcOiEnIlnjKU4Alg1x+j7aOk66vBwO2DBc/+fs2fAFr1fD1Huie/3poXiHELJRf3P5vMAeYzoWJ0bVDOvJMduGQeQBTarJYvN647O4lOz/q0Ehe7hxcKAuPrYSeIOjt7ejTX+Mcx2B6dEqZMDX530l14LBlakNlJ64os+Df8YmD5T3Ea2OkueUuoX/xq9fZK+KyxIN1G34I8RHw3bf5npomS6xyyzY8lOpgWgm//zr3Geu79RUZAVWL6luV8uPJvlj5qiyZz+GUggXzclxpSVbzhfDw9bvZl07kztpDRb3UDtX3HgIiU6dIZ6WjNUrqMfovVADO+3tk/2cMwS8oL5yiu7U409oKM/C15P2HckVbUSiDzxjt6N/CG6a/pcthwDX+N7lK8T7GFBmhmkQwEm5AkCJD/LmSqtOiG5Y=
  email:
    recipients:
    - patrique.legault@uottawa.ca
env:
  global:
    secure: VuIgpqkaQnVmn3qDzJOCr5qrD9cns874HFNBqzU3Yhm3EmJootr9nAOyGEFk8kI5gUEoJWh5XV30YFeT1d6QnwTHdFLaE3LTY3AMT4FOrbsZhPMeaKdl2nBEaCAVDqxTCWf7mQoJVu/7eg6lbDfw8T9mkjny4nDUXsXmXNBFoI3Wngzudm1Y4m5CF/IcOHugHL2zej8hwqMpDe1x3jABvvCtvtD7Ez0VXXK+rmMaQqZR2maKHlg6dv5h/LqIVqb65xB+ExEAuQ4w7akiBs0/9U3JcN9Hn43AbxcIddsvSPp75FEaeCR4Itwa/M4J6hf9m2l7gi6/tkcGNweTnlLmnb+E+JTPRj76oJ4TJhpQ11SsJq1QRTa2F+jV27BeaEF+MAEy1H9tAHyxikKkoU7mI8yG2kEEZzSLum7yYjfk4mgxYZv1EPcwiSnQvAxj7QsbTowxdtDPMOkRgnS0zM8MLoJOUW+SbFFKfZXuKI4iIAiyo7dL/gKr71w8QckGxG/UHSctrravX6zBv3JQa3yFUQPpSYgQBbENF/28dSxbbQ6ojvKV1XmsMOp07pf1z82O0vHANIkUNSfGFo7jELKDA1huUre9D5BydO5+X6rffH0Ea1ANBP6gCpE+WdQplQ1ArKiZxzxu8glEYOgUMpQKwmstjdxpYh2CrV1XxbejGHE=
