dist: xenial
branches:
  only:
  - master
  - develop
language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - script:
    - cd candidate-questions && mvn clean install && cd ..
    - cd documentation-questions && mvn clean install
stages:
- test
notifications:
  slack:
    secure: xhuIPz8DpmBhgivWajgpB0crqv67ltbihIaFuW0lPOVHp5L7kmd/pwE1yS4ncR7dNrh622yaxEKuLsGL4zX2Va1JbcifDy9VxRajErVmZiGUEedblddSZACE7DdVAk0xmvNQxdmPeCKggx0MeErvSOeW9GzqmLAWPXHn9Fo1j4VZ8+xXVlQnNcMvVzARtKB5ndwsJOKH/MGM71MD6ZpfaV2lrVISMuJyKAl6btWdwuGS6WhjwK5b4vv7FGHw19lRJwQiJQcOiEnIlnjKU4Alg1x+j7aOk66vBwO2DBc/+fs2fAFr1fD1Huie/3poXiHELJRf3P5vMAeYzoWJ0bVDOvJMduGQeQBTarJYvN647O4lOz/q0Ehe7hxcKAuPrYSeIOjt7ejTX+Mcx2B6dEqZMDX530l14LBlakNlJ64os+Df8YmD5T3Ea2OkueUuoX/xq9fZK+KyxIN1G34I8RHw3bf5npomS6xyyzY8lOpgWgm//zr3Geu79RUZAVWL6luV8uPJvlj5qiyZz+GUggXzclxpSVbzhfDw9bvZl07kztpDRb3UDtX3HgIiU6dIZ6WjNUrqMfovVADO+3tk/2cMwS8oL5yiu7U409oKM/C15P2HckVbUSiDzxjt6N/CG6a/pcthwDX+N7lK8T7GFBmhmkQwEm5AkCJD/LmSqtOiG5Y=
  email:
    recipients:
    - patrique.legault@uottawa.ca
env:
  global:
    secure: Xf88BMDKO8tgwkE7rn84zenOqYQOAeBbqbJFya/00EIqoTmp3fMrqW+fSnLiyu5bdsNs74cHiXBBKDMvZG8UlKHrU1P70cvH9HZ2pcA41pF807TdzbgKo6nabPfCK5FKYO0GlV5MwHaOWxJF3skjImtpluc7h6lJfXuRgNUWBRx3MmYidyr1lnFpt+9O7RIYkm5Du7IoTOomUtqf3n0e3BBwHARoSTfTcTwCUG2nuhfz9hUKPTSFZ+Rwqek9BzZVhuCHrai3WHUbkjJi3Y0dZR6AHA0Zy7WmCfC0+5lkeDtCaFWerB9u1x+YxeN+ezeOROljCDQNHad5fg5QQ6xFXdHRu2hhgle5HLnH3L2ikBEW0hcriNRfRj0bze43LzCyjv1+IXHMb9r+/RTKtQzuif/AjHIQsu3WqMd1874KaVP5mTfUdWPx+KXRLZ1e7TfXxohSL4SiB5X0zB8d/oJI6VICqSD0JdmZGNp5bNoUKzvsqCzPF4DgZnF2XWoBfsW1CzNI5qirKWJju1RrWqurQGnCa2JnctKnKO1fruTwphvT4praQGUIAzVc3bjhWIxFUpc3Nw8FBPqcXRmD2RGm7WjNdV6OZ4qK3nQPfm/xgsfsbCAWX9TjGZFiqk5Tljg8tetgywK6HYONWZfoF0FHrkoC7fMBYTYJr/w6amdykwk=
