#safelist
branches:
  only:
      - master
      - develop
sudo : false
language: java
jdk:
  - openjdk11
cache:
    directories:
        - $HOME/.m2
jobs: 
  include: 
    - stage: compile
      before_script:
        - cd candidate-questions
      script:
        - mvn clean install
        - mvn javadoc:javadoc

stages: 
        - compile

notifications:
        slack: outreach-uottawa:VO2Yf1Vx0aCVpwGEqTx3tRjd
        email:
            recipients:
                - patrique.legault@uottawa.ca