#safelist
branches:
  only:
      - master
      - develop
language: java
jdk:
  - openjdk11
cache:
    directories:
        - $HOME/.m2
jobs: 
  include: 
    - stage: compile_developer
      before_script:
        - cd candidate-questions
      script:
        - mvn clean install
        - mvn clean javadoc:javadoc
    - stage: compile_documenter
      before_script:
        - cd ../documentation-questions
      script:
        - mvn clean install
stages: 
  - compile_developer
  - compile_documenter
notifications:
        slack: outreach-uottawa:VO2Yf1Vx0aCVpwGEqTx3tRjd
        email:
            recipients:
                - patrique.legault@uottawa.ca