dist: xenial
branches:
  only:
  - master
  - develop
language: node_js
node_js: '10'
jdk:
- openjdk11
addons:
  apt:
    packages:
    - openjdk-8-jdk
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - script:
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/candidate-questions/server-questions
      && mvn clean install
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/candidate-questions/client-questions
      && npm install && npm run lint && npm run build && npm run test
    - cd $HOME/build/AES-Outreach/Outreach-Interviews/documentation-questions && mvn
      clean install
    name: Build Outreach-Interviews
stages:
- test
notifications:
  slack:
    secure: xhuIPz8DpmBhgivWajgpB0crqv67ltbihIaFuW0lPOVHp5L7kmd/pwE1yS4ncR7dNrh622yaxEKuLsGL4zX2Va1JbcifDy9VxRajErVmZiGUEedblddSZACE7DdVAk0xmvNQxdmPeCKggx0MeErvSOeW9GzqmLAWPXHn9Fo1j4VZ8+xXVlQnNcMvVzARtKB5ndwsJOKH/MGM71MD6ZpfaV2lrVISMuJyKAl6btWdwuGS6WhjwK5b4vv7FGHw19lRJwQiJQcOiEnIlnjKU4Alg1x+j7aOk66vBwO2DBc/+fs2fAFr1fD1Huie/3poXiHELJRf3P5vMAeYzoWJ0bVDOvJMduGQeQBTarJYvN647O4lOz/q0Ehe7hxcKAuPrYSeIOjt7ejTX+Mcx2B6dEqZMDX530l14LBlakNlJ64os+Df8YmD5T3Ea2OkueUuoX/xq9fZK+KyxIN1G34I8RHw3bf5npomS6xyyzY8lOpgWgm//zr3Geu79RUZAVWL6luV8uPJvlj5qiyZz+GUggXzclxpSVbzhfDw9bvZl07kztpDRb3UDtX3HgIiU6dIZ6WjNUrqMfovVADO+3tk/2cMwS8oL5yiu7U409oKM/C15P2HckVbUSiDzxjt6N/CG6a/pcthwDX+N7lK8T7GFBmhmkQwEm5AkCJD/LmSqtOiG5Y=
  email:
    recipients:
    - patrique.legault@uottawa.ca
env:
  global:
    secure: eYfQhcQbHp6VSS0G/xj++h+CRDdPwNjdv19sk6+7r2qtfTVdENKxHy8wOte+F4W209CnqqOJSy+h7OiiV+6j1jt5XeXAwjzBVHKoSvCkwScLzVYJ/YQK4HI/FxIURqv8i7ldWzyloyROT6dK0AlNDlekE/1oqPsExHxDDwwrxnBpOMTk8oYSzNijdeEpmmcGwFzqEOkr6c710VadzyLYk27MoRQIeKXhV1paQy5Bg/C5axoA5vXMFBRDKnRFGgbj3/6de+mdRVXoY+m8I6gRdzM49dXuXJvShqu18Z2gQO0h/An+96/Sz9vc7twlxWRM782wVkqYzKf2Rrjiel1h64wDGwyCDLDElcdk7BDbzdCh/2h1kgPA87mbNenqkIzfbbw9jUvfrA3o9OJUkQk2UYpP3pCRzakxTzgHgSrCSmMstKApTY8UXpg4/bRI7B8gpEaW6umulNBfx5equQWvpPP+q5SUcduayiPN682sVeGc5c597W5aJzEoUTWLUv7/R1E1d7O4ZAW8mWD2SPcQ0cw7Oc6rV6Ihu9mtLKOF11bRNeii5GlY+Zk0UUSrutObaDw4NoNaavXIQdaB1fNTJ2Z0tfouI0epaQJFa9ik2CCk0jvv60Eu/2uuYEuvKn8Z4HbEuiPAfNuao6mJj7SfnS/bDtf9iIE+tKifbJ9EriQ=
