#safelist
branches:
  only:
    - master
    - develop
language: java
jdk:
  - openjdk11
cache:
  directories:
      - $HOME/.m2
jobs: 
  include:
    - script:
        - cd candidate-questions && mvn clean install
        - cd documentation-questions && mvn clean install
stages: 
  - test
notifications:
  slack: outreach-uottawa:VO2Yf1Vx0aCVpwGEqTx3tRjd
  email:
    recipients:
        - patrique.legault@uottawa.ca